#!/usr/bin/env php
<?php
define('HF_INSTALLER', rtrim(__DIR__, '/\\'));
define('DS', DIRECTORY_SEPARATOR);
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application('Helpflow Installer', '1.0.0');

$application->add(new \Helpflow\Installer\InstallCommand());
$application->add(new \Helpflow\Installer\UpdateCommand());
$application->add(new \Helpflow\Installer\LicenseKeyCommand());

$application->run();
